site_name: "T2000食譜Collection"
site_url: https://t2000chris.github.io/cooking-recipes/
theme:
  name: material
  language: en
  features:
    - navigation.tabs            # ❌ turn OFF tabs so sections expand instead of navigating
    - navigation.tabs.sticky
    # - navigation.sections          # ✅ show folders as groups
    # - navigation.prune             # ✅ (optional) only show the current section in the sidebar
    # - navigation.indexes         # ❌ keep OFF so section labels aren't links

    - search.suggest
    - search.highlight
    - toc.follow
  palette:
    - scheme: default
      primary: teal
      accent: dark orange
  font:
    text: Noto Sans
    code: JetBrains Mono
  icon:
    logo: material/silverware-fork-knife
    repo: fontawesome/brands/github
extra_css:
  - assets/styles/recipes.css
  #- assets/styles/override.css
extra_javascript:
  - http://homeassistant:8123/local/send-to-kitchen.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/t2000chris/cooking-recipes
      name: GitHub
plugins:
  - search:
      lang: [en, zh]
      separator: '[\s\-。，、；；：：]+'
  - tags
  - awesome-pages
  - minify:
      minify_html: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets



