site_name: "T2000's Cooking Recipes Collection"
site_url: https://t2000chris.github.io/cooking-recipes/
repo_url: https://github.com/t2000chris/cooking-recipes
theme:
  name: material
  language: en
  features:
    - navigation.tabs          # top tabs for top-level sections (mobile = swipeable)
    - navigation.sections      # group pages within a section
    - navigation.prune         # show only the current section in the sidebar (lighter on mobile)
    - navigation.indexes       # make folder index.md the landing for each tab/section
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.follow
  palette:
    - scheme: default
      primary: deep orange
      accent: amber
  font:
    text: Noto Sans
    code: JetBrains Mono
  icon:
    logo: material/silverware-fork-knife
    repo: fontawesome/brands/github
extra_css:
  - assets/styles/recipes.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/t2000chris/cooking-recipes
      name: GitHub
plugins:
  - search:
      lang: [en, zh]
      separator: '[\s\-。，、；；：：]+'
  - tags
  - awesome-pages
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets

