site_name: T2000's Cooking Recipes Collection
site_url: https://t2000chris.github.io/cooking-recipes/
repo_url: https://github.com/t2000chris/cooking-recipes
theme:
  name: material
  language: zh-TW
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  palette:
    - scheme: default
      primary: teal
      accent: orange
extra_css:
  - styles/recipe.css

plugins:
  - search
  - awesome-pages
  - tags
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true


