site_name: T2000's Cooking Recipes Collection
site_url: https://t2000chris.github.io/cooking-recipes/
repo_url: https://github.com/t2000chris/cooking-recipes
theme:
  name: material
  language: zh_TW
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  palette:
    - scheme: default
      primary: teal
      accent: orange
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight
extra_css:
  - styles/recipe.css
  

plugins:
  - search
  - awesome-pages
  - tags
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true


